apiVersion: v1
kind: Service
metadata:
  name: angular-ui
  labels:
    app: angular-ui
    component: ui
    version: "1.5.0"
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: angular-ui
    component: ui
    version: "1.5.0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-ui
  labels:
    app: angular-ui
    component: ui
    version: "1.5.0"
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: angular-ui
      component: ui
      version: "1.5.0"
  template:
    metadata:
      labels:
        app: angular-ui
        component: ui
        version: "1.5.0"
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: angular-ui
        image: ccr.ccs.tencentyun.com/pulse-line-beta/angular-observe:1.5.0
        # resources:
        # requests:
        #   memory: 100M
        #   cpu: 100m
        # limits:
        #   memory: 250M
        #   cpu: 250m
        ports:
        - containerPort: 80
        imagePullPolicy: Always
