apiVersion: v1
kind: Service
metadata:
  name: service-e
  labels:
    app: service-e
    component: service
    version: "1.5.0"
spec:
  ports:
  - name: http2
    protocol: TCP
    port: 50051
  selector:
    app: service-e
    component: service
    version: "1.5.0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-e
  labels:
    app: service-e
    component: service
    version: "1.5.0"
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: service-e
      component: service
      version: "1.5.0"
  template:
    metadata:
      labels:
        app: service-e
        component: service
        version: "1.5.0"
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: service-e
        image: ccr.ccs.tencentyun.com/pulse-line-beta/go-srv-e:1.5.0
        # resources:
        # requests:
        #   memory: 100M
        #   cpu: 100m
        # limits:
        #   memory: 250M
        #   cpu: 250m
        ports:
        - containerPort: 50051
        imagePullPolicy: Always
