apiVersion: v1
kind: Secret
metadata:
  name: go-srv-config
type: Opaque
data:
  mongodb.conn: bW9uZ29kYjovL3Rlc3Q6dGVzdEBtb25nb2RiLnBsLXRlc3Quc3ZjLmNsdXN0ZXIubG9jYWw6MjcwMTcvYWRtaW4=
  rabbitmq.conn: YW1xcDovL3BsOnRlc3RAcmFiYml0bXEucGwtdGVzdC5zdmMuY2x1c3Rlci5sb2NhbDo1NjcyLw==
